name: Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@master
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: Run unit tests
      run: go test ./...
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
